extends: existence
message: "Admonition content should end with a period."
level: error
scope: raw
raw:
  # - '(?<=\?\?\?.*?\n\s{4,}.*[^.?!]\]\]?(?!\]))\n'
  - '(?<!^---)(?:(?!^---$).)*(?<=\?\?\?.*?\n\s{4,}.*[^.?!]\]\]?(?!\]))\n'
